sudo: false
language: node_js
node_js:
  - "8"
before_install:
  - npm install -g codecov
script:
  - npm run test
  - npm run test:bs
after_success:
  - codecov
after_failure:
  - codecov
env:
  global:
    - secure: ETNp2dqlAtuktlUiIcYzNy98BLbyrW6a3zyeTnS9X8/DFCQ3jYzZkVFm5kt3QyGzkDo7s2F4LHQf34aJFQK3fYteUuAECHGZXM5CPAquOcACqUuW9yJzvkfgppBj9OOD8V2kA0XBAE+W2yEq+XuFEyPcuE7uq0U+r32KGYbZc5WWElrSvp5DKkoD6ZisKL0bhZcczXyqDAuz/WnmIhwn/f/Nc8vXKxEPl6UJGcL22dtgHnZU6rmeS8VW72lgUWKqIWzLV17BT+J6it05ETBoBsOzjMs+iS7kz/bd1mFFoBrlacdIRnxTe16hZCpHtoXjjHudsiTM1lCSgOsE/Fpel0EH6VPIyYbIc0bCnt2dCPzJPXuuCteax88YXevMxmY3c6fmCUZ53HUeU6HdubtzNu0XB/FJi86guK06zs/KWyB9hN5IkXmLV0ywbYpposVoR2L0kewBgggcsOJLxg6uugeDkX660588EImMY/ve1PJkNG7WIDHcFK9Rc5CinGoM0SXxjEYvCoa0BIvhFgTXd/tLtJgqVlHw6VOG3X0o9Kk/nZbuNDPgVgyC96obO7OObG72DnFLSKE2wTWI9mGYWHvXyGAoP1vizCqw0bc5O3TADb/9woz86HiR0XjdKGCgU5d5dlAJ/Rl98NrYKjlFdmkgXDKQp0yoj8dUxrqsDXo=
    - secure: vCpDybPhDdiTEmS3aJVtxrq9Ls2FJ6eh1OUqMnp2Xhlji1nvfOaVuUankc98DdCyH9BPTLWrUuxyN5Po+xuteeZ/rq72L1wY7fYckdPgqNZkv3sEqlSO6ECcdlF64bIcVNoPg7WCq/GsBeQHxE+uE9ljKHavGgSOJ4gMeIo2RXRH6hmPTePP/sFRePjC4loMfsmoPJSK5ce/m4fTk+VNNh9aN8rvyn1tWy504BffSREgrZ+NRXCqkQDbcsjZyoGszY5RlR4qe8XVvNa8Mshgg6Wm7k1B3qe237C0geLc8HjUT+kdQT1MUEegodjG8G4k73WDDckqQsVi6awD6SFosShJr84E5ZGKpA5XypmbLXsqsQi7bmETCSG+GogI3tHp2SIq0dhqzQgbCjeR2oqQlQJb5QLCc0z735DDUHSajEtSXzrUcxvORrh8MZaBeDx08HGqHU5qpKiIhRvQZB7GEQBIEMA9ACHBMgaZA+AnGFQoHnPxKPvlWKbYUeeRZPZkftTnfsIFMcIPH3slrSauDzRCvXeXE1q49xEaiAqkK2wyPK7m0VXcv0gNXA0fDN0IbshHikO7vQIlnMCk/bJnge0+RiaQyP57+M4mPuYM5EyXUNASxZNWE8EPAOcYJlAGD8MIIaATxkoANm7aEyjyTF7Wb+yLy/mMMAaSxhJYZwo=
addons:
  chrome: stable
deploy:
  provider: npm
  email: npm@t-code.pl
  api_key:
    secure: Zlw/jlTSZdWh9C7WfXfh/X/WgCNmgBuRNAJZQThJ9fryWoQbWBoQf4qCOjXMF6e8I0VnKMAOmEq6Iu7d3NH2gijyc52dzXKeIzyf8j05KTm6swN4ox1Mnaxgm0NJDEqBHYorua78PNYPzCrsKYJ1qiwaciXyoY2Y1bYvBZtONqlBOGIPv2EP6/skGAMli+8kFiYfsSndW6omrqtUT9t5SV8J/57dn3VHQDq8twrT7F9oTSiHOA0n6eiOneuy3D6V0hHsgsFbRe/0gZxTVz/Ygf093ooa0HU1npgG5+h4R6UQiLuMiHD9sFS2dOcQBI67EuKcxBf4iVGoMN/NtksyoZY3rR5w/kSRWVwdW/Fh2wLITQs5N/JDlehi+PA7hGbtWOhSvCp9+TBVivns9fvgQhTxwG2Kp8Yx0+KpHJABPJa6cjizATAOlxOMV9coEvZLsPXcqpxCFEYyd6fmacKgL+Cd2MAthiabNuXr+FmtzNH7kgwX438vV1RWD8/KlPeyzkMAvvk/q/avHuZMh+zEOSOCpO2NeCttEuQL/l9Zef6h1L/WOBOw/6DxCIGFJ3S9hvxIjV0lIFicM6PyoC/iTAnrrbM8FbKA118jsYj3B/Nhdm3UtDNY8VdEHpmVJjFDrkuzwO/jiBHPChEW7hs5VPWwoCCUY1Eq50kvlqGbg7E=
  on:
    tags: true
    repo: hypermedia-app/lit-any-components-vaadin
    branch: build-tooling-updates
  skip_cleanup: true
